### ISSUE TITLE
Multiple users report that the settings are visible and frozen

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/youtube-ambilight#39]
- [ ] ~~Contact users that leave their contact info when providing feedback via the form. Are you a user with this issue? Then please leave your feedback here or email me at wezelkrozum@gmail.com so we can debug and fix it together!~~
- [ ] ~~Find the cause~~
- [ ] ~~Fix the issue~~
- [x] Apply visual workaround by keeping the timeline visible

**Reports:**
| Date | Version | Browser | Problem |
| -- | -- | -- | -- |
2020/02/01 04:32:03 | 2.32 | Opera 66.0.3515.44 | Always open
2020/02/19 04:31:20 | 2.33.5 | Edge | Always open
2020/03/13 01:02:42 | 2.33.5 | Edge | Never open
2020/03/21 05:28:19 | 2.33.5 | Opera | Always open
2020/03/21 11:41:39 | 2.33.5 | Opera | Always open

**Possible stacktrace for no settings button**
```
TypeError: Cannot read property 'prepend' of null
  at HTMLButtonElement.HTMLElement.prependTo(chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:30:10)
  at Ambilight.initSettingsMenu(chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:4301:28)
  at Ambilight.initSettings(chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:3281:12)
  at new Ambilight(chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:2849:12)
  at tryInitAmbilight(chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:4644:24)
  at ambilightDetectVideoPage(chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:4670:9)
  at ? (chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:4693:7)
  at ? (chrome-extension://paponcgjfojgemddooebbgniglhkajkj/scripts/youtube-ambilight.js:4700:2)
```

**Comment by WesselKroos** [comment]
Might  be related to #34

**Comment by WesselKroos** [comment]
It might be visually incorrect due to the fact that the timeline is hidden when the settings are still open.

- [x] Keep the timeline visible when the settings are open
